"""test update for including scores

Revision ID: 4470f47b0ee0
Revises: b39b65b28135
Create Date: 2022-03-17 15:54:00.037307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4470f47b0ee0'
down_revision = 'b39b65b28135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('attacker_id', sa.Integer(), nullable=True),
    sa.Column('defender_id', sa.Integer(), nullable=True),
    sa.Column('attacker_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['defender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_result_timestamp'), 'match_result', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_result_timestamp'), table_name='match_result')
    op.drop_table('match_result')
    # ### end Alembic commands ###
