"""empty message

Revision ID: 8d6394f53dcf
Revises: 
Create Date: 2022-04-18 20:45:57.816684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6394f53dcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=96), nullable=True),
    sa.Column('password_hash', sa.String(length=102), nullable=True),
    sa.Column('sciper', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sciper')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('member1_id', sa.Integer(), nullable=True),
    sa.Column('member2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['member2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member1_id'),
    sa.UniqueConstraint('member2_id')
    )
    op.create_index(op.f('ix_team_team_name'), 'team', ['team_name'], unique=True)
    op.create_table('defence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defender_team_id', sa.Integer(), nullable=True),
    sa.Column('utility', sa.PickleType(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['defender_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defence_round'), 'defence', ['round'], unique=False)
    op.create_index(op.f('ix_defence_timestamp'), 'defence', ['timestamp'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defender_team_id', sa.Integer(), nullable=True),
    sa.Column('attacker_team_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['defender_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defender_team_id', 'attacker_team_id', 'round', name='_match_pair_once_per_round')
    )
    op.create_index(op.f('ix_match_round'), 'match', ['round'], unique=False)
    op.create_table('attack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('results', sa.PickleType(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_timestamp'), 'attack', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attack_timestamp'), table_name='attack')
    op.drop_table('attack')
    op.drop_index(op.f('ix_match_round'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_defence_timestamp'), table_name='defence')
    op.drop_index(op.f('ix_defence_round'), table_name='defence')
    op.drop_table('defence')
    op.drop_index(op.f('ix_team_team_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
